### ISSUE TITLE
Insertion of a lot of CSS and JS in the front-end

### ISSUE THREAD

**Issue by echantigny** [MilkshakeStudio/craft-conditions#5]
Hi,

I was happy to see that conditionals fields were making their way back to Craft 3.   Thanks for doing that.

Unfortunately, I also noticed that there's a lot of CSS and JS being injected into my front-end template, messing with a lot of the styles in the site.

See the screen shot of the same page with and without your plugin enabled.

![2019-05-22 11_29_22-DevTools - autocourse local_series](https://user-images.githubusercontent.com/4933333/58187656-33057100-7c85-11e9-9147-d9ba08ba32de.png)

![2019-05-22 11_28_54-DevTools - autocourse local_series](https://user-images.githubusercontent.com/4933333/58187658-34369e00-7c85-11e9-993b-6e58f4276353.png)

**Comment by echantigny** [comment]
Actually, it looks like this issue is fixed in 1.0.2, but that's not pushed to the Craft Store or packagist because composer.json has the wrong version number.

**Comment by jpcarpenter** [comment]
@echantigny can you explain the steps to take in order to fix this? I've attempted to change the version  number as you did, ran `composer update` and `composer require craftconditions/conditions 1.0.3`, but Craft still says it cannot find a version matching that number.

**Comment by echantigny** [comment]
There's no way to fix it on our end, it needs to be fixed here, in the repo.  I sent a Pull request to fix it but no news.

**Comment by jpcarpenter** [comment]
I understand. I've sent an issue report to issues@craftcms.com, so hopefully that may push things along.

**Comment by echantigny** [comment]
@jpcarpenter This has nothing to do with Craft (Pixel & Tonic) though.  This is strictly an issue with the composer.json file in this specific repo, which is MilkshakeStudio.

**Comment by Slgoetz** [comment]
Composer and Packagist have been updated

**Comment by jpcarpenter** [comment]
@Slgoetz that fixed the initial problem. Now there seems to be a new issue. Stack trace below:

```
yii\base\UnknownPropertyException: Getting unknown property: craftconditions\conditions\records\ConditionalsRecord::expressions in /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('expressions')
#1 /Users/user/Documents/Sites/mysite/vendor/craftconditions/conditions/src/Conditions.php(254): yii\db\BaseActiveRecord->__get('expressions')
#2 /Users/user/Documents/Sites/mysite/vendor/craftconditions/conditions/src/Conditions.php(178): craftconditions\conditions\Conditions->getConditionalObj()
#3 /Users/user/Documents/Sites/mysite/vendor/craftconditions/conditions/src/Conditions.php(155): craftconditions\conditions\Conditions->jsonToJs()
#4 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/BaseObject.php(109): craftconditions\conditions\Conditions->init()
#5 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#6 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('conditions', Object(craft\web\Application), Array)
#7 [internal function]: craft\base\Plugin->__construct('conditions', Object(craft\web\Application), Array)
#8 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#9 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craftconditions...', Array, Array)
#10 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craftconditions...', Array, Array)
#11 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#12 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('conditions', Array)
#13 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/base/ApplicationTrait.php(1228): craft\services\Plugins->loadPlugins()
#14 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#15 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#16 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#17 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#18 [internal function]: craft\web\Application->__construct(Array)
#19 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#20 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#21 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#22 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#23 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/bootstrap/web.php(52): require('/Users/user...')
#24 /Users/user/Documents/Sites/mysite/public/index.php(20): require('/Users/user...')
#25 {main}
```
