### ISSUE TITLE
Getting unknown property: craftconditions\conditions\records\ConditionalsRecord::expressions

### ISSUE THREAD

**Issue by jpcarpenter** [MilkshakeStudio/craft-conditions#7]
After installing the plugin, the following error appears:

```
yii\base\UnknownPropertyException: Getting unknown property: craftconditions\conditions\records\ConditionalsRecord::expressions in /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/db/BaseActiveRecord.php(298): yii\base\Component->__get('expressions')
#1 /Users/user/Documents/Sites/mysite/vendor/craftconditions/conditions/src/Conditions.php(254): yii\db\BaseActiveRecord->__get('expressions')
#2 /Users/user/Documents/Sites/mysite/vendor/craftconditions/conditions/src/Conditions.php(178): craftconditions\conditions\Conditions->getConditionalObj()
#3 /Users/user/Documents/Sites/mysite/vendor/craftconditions/conditions/src/Conditions.php(155): craftconditions\conditions\Conditions->jsonToJs()
#4 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/BaseObject.php(109): craftconditions\conditions\Conditions->init()
#5 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#6 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('conditions', Object(craft\web\Application), Array)
#7 [internal function]: craft\base\Plugin->__construct('conditions', Object(craft\web\Application), Array)
#8 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#9 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craftconditions...', Array, Array)
#10 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craftconditions...', Array, Array)
#11 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#12 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('conditions', Array)
#13 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/base/ApplicationTrait.php(1228): craft\services\Plugins->loadPlugins()
#14 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#15 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#16 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#17 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#18 [internal function]: craft\web\Application->__construct(Array)
#19 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#20 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#21 /Users/user/Documents/Sites/mysite/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#22 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#23 /Users/user/Documents/Sites/mysite/vendor/craftcms/cms/bootstrap/web.php(52): require('/Users/user...')
#24 /Users/user/Documents/Sites/mysite/public/index.php(20): require('/Users/user...')
#25 {main}
```

_Originally posted by @jpcarpenter in https://github.com/MilkshakeStudio/craft-conditions/issues/5#issuecomment-497011825_

**Comment by Slgoetz** [comment]
hey @jpcarpenter - Can you give a bit more details on where you see this error, what version you're on (basically your composer file).
